### ISSUE TITLE
Is notification script for checkmk working?

### ISSUE THREAD

**Issue by tyctor** [ADMIN-INTELLIGENCE-GmbH/CheckMK#3]
**CMK version: OMD - Open Monitoring Distribution Version 2.2.0p25.cce**
**OS version: Ubuntu 22.04.4 LTS**

I have custom ntfy script for notification sending found here: https://forum.checkmk.com/t/notification-script-for-ntfy-sh/40875

![Capture 2024-05-09 at 17 43 28](https://github.com/ADMIN-INTELLIGENCE-GmbH/CheckMK/assets/44854182/7cdc9bfc-8b4f-4167-965f-ad1fa721b0dc)

When i testing sending with `Fake check results` nothing is send
Is there something special to enable sending notifications?

I am looking forward to your answer.

**Comment by Man-in-Black** [comment]
Solved like mentioned in the Checkmk community
https://forum.checkmk.com/t/custom-notification-is-not-sending/46745
